uat keywords added
adsabs/ADSDataPipeline pull request #44
Opened 2023-12-11 07:47 UTC by mugdhapolimera

Note: The all.links file is a temporary file with fake entries only for testing.

2023-12-12 23:20 UTC, kelockhart requested changes
We'll want to include the UAT IDs in here too, so let's think more about how to do that.

2023-12-12 23:20 UTC, kelockhart commented on adsdata/tests/data1/config/links/uat/all.links
I know this is a test file only, but I think we're going to have to include the UAT ID in here too, since there can be some duplication in labels.

If we do that, it may make more sense for this to be a multiline file of the format:
`bibcode <tab> UAT label <tab> UAT ID`

2023-12-12 23:20 UTC, kelockhart commented on adsdata/file_defs.py
> +data_files['uat'] = {'path': 'links/uat/all.links', 'default_value': [], 'multiline': False}
See my note about the multiline on the test file below

2023-12-13 09:03 UTC, mugdhapolimera commented on adsdata/tests/data1/config/links/uat/all.links
Yes, I realised this yesterday after the PR was created. Additionally, we also need to capture each UAT label's lineage. so I propose something like this:

bibcode <tab> UAT label parent level 1 <tab> UAT label parent level 2 .... <tab> UAT label parent n <tab> UAT label <tab> UAT ID

This would require multiline = True. 
I can change this to substitute the <tab> chars for '/' in masterpipeline as done for gpn.

2023-12-20 08:20 UTC, mugdhapolimera commented
Note: UAT ID will be added in masterpipeline as done for gpn field

2023-12-20 20:58 UTC, kelockhart approved these changes

2023-12-27 17:22 UTC, merged